name: oro
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  flutter_svg: ^0.12.0
  sensors: ^0.4.0+1
  rxdart: ^0.21.0
  bloc_provider: ^0.5.0+3
  location: ^2.0.0
  http: ^0.12.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
   - a/logo.svg
   - a/s.svg
   - a/place.svg
   - a/1.svg
   - a/2.svg
   - a/3.svg

  fonts:
    - family: Averta
      fonts:
        - asset: fonts/Averta-Regular.otf