name: oro
description: Air quality app for Flutter Create.

version: 1.0.3+4

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  flutter_svg: ^0.12.0
  sensors: ^0.4.0+1
  rxdart: ^0.21.0
  bloc_provider: ^0.5.0+3
  location: ^2.0.0
  http: ^0.12.0+1
  flare_flutter: ^1.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
   - assets/load.svg
   - assets/place.svg
   - assets/home.svg
   - assets/star.svg
   - assets/good.flr
   - assets/excellent.flr
   - assets/moderate.flr
   - assets/bad.flr
   - assets/shake.flr
   - assets/shake2.flr
   - assets/text.json
   - assets/01d.svg
   - assets/01n.svg
   - assets/02d.svg
   - assets/02n.svg
   - assets/03d.svg
   - assets/04d.svg
   - assets/09d.svg
   - assets/10d.svg
   - assets/10n.svg
   - assets/11d.svg
   - assets/13d.svg
   - assets/50d.svg

  fonts:
    - family: Averta
      fonts:
        - asset: fonts/Averta-Regular.otf
        - asset: fonts/Averta-Thin.otf
          weight: 200
        - asset: fonts/Averta-SemiBold.otf
          weight: 500
        - asset: fonts/Averta-Bold.otf
          weight: 600
        - asset: fonts/Averta-ExtraBold.otf
          weight: 800