name: oro
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  flutter_svg: ^0.12.0
  sensors: ^0.4.0+1
  rxdart: ^0.21.0
  bloc_provider: ^0.5.0+3
  location: ^2.0.0
  http: ^0.12.0+1
  flare_flutter: ^1.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
   - assets/logo.svg
   - assets/s.svg
   - assets/s2.svg
   - assets/load.svg
   - assets/p.svg
   - assets/home.svg
   - assets/star.svg
   - assets/1.flr
   - assets/2.flr
   - assets/3.flr
   - assets/shake.flr
   - assets/shake2.flr

  fonts:
    - family: Averta
      fonts:
        - asset: fonts/Averta-Regular.otf
        - asset: fonts/Averta-Thin.otf
          weight: 200
        - asset: fonts/Averta-SemiBold.otf
          weight: 500
        - asset: fonts/Averta-Bold.otf
          weight: 600
        - asset: fonts/Averta-ExtraBold.otf
          weight: 800